package com.tmqt.dao;

import com.tmqt.model.Factory;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "FactoryMapper")
public interface FactoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated
     */
    int insert(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated
     */
    int insertSelective(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated
     */
    Factory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Factory record);

    List<Factory> selectByName(String factoryName);

    List<Factory> selectAll();

    int countFactory();

    String selectNameById(int factoryid);
}