package com.tmqt.dao;

import com.tmqt.model.Newproduct;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component(value = "NewproductMapper")
public interface NewproductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newproduct
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newproduct
     *
     * @mbg.generated
     */
    int insert(Newproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newproduct
     *
     * @mbg.generated
     */
    int insertSelective(Newproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newproduct
     *
     * @mbg.generated
     */
    Newproduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Newproduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newproduct
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Newproduct record);


    List<Newproduct> selectAll();

    List<Newproduct> selectByCode(String code);

    List<Newproduct> selectByIf(Map conditions);

    int countNewProduct();
}