package com.tmqt.dao;

import com.tmqt.model.Outbill;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component(value = "OutbillMapper")
public interface OutbillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbill
     *
     * @mbg.generated
     */
    int insert(Outbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbill
     *
     * @mbg.generated
     */
    int insertSelective(Outbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbill
     *
     * @mbg.generated
     */
    Outbill selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Outbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outbill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Outbill record);

    List<Outbill> selectAll();

    List<Outbill> selectByIf(Map conditions);

    int countOutbill();
}