package com.tmqt.dao;

import com.tmqt.model.Productplan;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component(value = "ProductplanMapper")
public interface ProductplanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productplan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productplan
     *
     * @mbg.generated
     */
    int insert(Productplan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productplan
     *
     * @mbg.generated
     */
    int insertSelective(Productplan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productplan
     *
     * @mbg.generated
     */
    Productplan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productplan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Productplan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productplan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Productplan record);

    List<Productplan> selectAll();

    List<Productplan> selectByCode(String code);

    List<Productplan> selectByIf(Map conditions);

    int countProductPlan();
}