package com.tmqt.dao;

import com.tmqt.model.Purchase;
import com.tmqt.model.PurchaseExcelEntity;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component(value = "PurchaseMapper")
public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int insert(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int insertSelective(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    Purchase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Purchase record);

    /*
     *查询全部进货记录
     */
    List<Purchase> selectAll();

    /*
     *条件查询进货记录
     */
    List<Purchase> selectByIf(Map conditions);

    /*
     *统计进货记录条数
     */
    int countPurchase();

    /*
     *通过进货订单id删除进货记录
     */
    int deleteByBillId(String billid);

    /*
     *根据billid查找进货记录
     */
    List<Purchase> selectByBillId(String billid);

    List<PurchaseExcelEntity> selectPurExcEntityByBillId(String billid);
}