package com.tmqt.dao;

import com.tmqt.model.Rangesize;
import org.springframework.stereotype.Component;

import java.util.List;

@Component(value = "RangesizeMapper")
public interface RangesizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangesize
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangesize
     *
     * @mbg.generated
     */
    int insert(Rangesize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangesize
     *
     * @mbg.generated
     */
    int insertSelective(Rangesize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangesize
     *
     * @mbg.generated
     */
    Rangesize selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangesize
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Rangesize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rangesize
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Rangesize record);

    List<Rangesize> selectBySize(String rangeSize);

    List<Rangesize> selectAll();

    int countRangesize();

    String selectRangesizeById(int rangeSizeId);
}