package com.tmqt.dao;

import com.tmqt.model.ReturnExcelEntity;
import com.tmqt.model.Returns;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component(value = "ReturnsMapper")
public interface ReturnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returns
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returns
     *
     * @mbg.generated
     */
    int insert(Returns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returns
     *
     * @mbg.generated
     */
    int insertSelective(Returns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returns
     *
     * @mbg.generated
     */
    Returns selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returns
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Returns record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returns
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Returns record);

    List<Returns> selectAll();

    List<Returns> selectByIf(Map conditions);

    int countReturns();

    /*
     *通过进货订单id删除退货记录
     */
    int deleteByBillId(String billid);

    /*
     *根据billid查找退货记录
     */
    List<Returns> selectByBillId(String billid);

    List<ReturnExcelEntity> selectRetExcEntityByBillId(String billid);
}