server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  #onlinePort: 80
  #localPort:8080


spring:
    thymeleaf:
        prefix: classpath:templates/
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        mode: HTML5
        cache: false
    resources:
      static-locations: classpath:templates/
        #静态资源扫描
    datasource:
        name: test
        #url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/tmqt?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/tmqt?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: xxx
        password: xxx
        #onlinePassword打包用这个: xxx
        #localPass:xxx

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    #腾讯云存储依赖
    tengxun:
        #密匙
        secretId: xxx
        secretKey: xxx
        #所在区域
        bucket: xxx
        #储存桶名称
        bucketName: xxx
        #访问路径
        path: xxx
        #路径前缀
        pathHead: tmqt-1
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.tmqt.model
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #pagehelper分页插件
  pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql
logging:
  config: classpath:log/logback-spring.xml



