package com.tmqt.model;

import java.util.Date;

public class Factory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.factoryname
     *
     * @mbg.generated
     */
    private String factoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.id
     *
     * @return the value of factory.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.id
     *
     * @param id the value for factory.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.factoryname
     *
     * @return the value of factory.factoryname
     *
     * @mbg.generated
     */
    public String getFactoryname() {
        return factoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.factoryname
     *
     * @param factoryname the value for factory.factoryname
     *
     * @mbg.generated
     */
    public void setFactoryname(String factoryname) {
        this.factoryname = factoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.address
     *
     * @return the value of factory.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.address
     *
     * @param address the value for factory.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.addtime
     *
     * @return the value of factory.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.addtime
     *
     * @param addtime the value for factory.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}