package com.tmqt.model;

import java.util.Date;

public class Inbill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbill.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbill.factoryid
     *
     * @mbg.generated
     */
    private Integer factoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbill.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbill.verifystate
     *
     * @mbg.generated
     */
    private Integer verifystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbill.allnumber
     *
     * @mbg.generated
     */
    private Integer allnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbill.allprice
     *
     * @mbg.generated
     */
    private Float allprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbill.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inbill.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbill.id
     *
     * @return the value of inbill.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbill.id
     *
     * @param id the value for inbill.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbill.factoryid
     *
     * @return the value of inbill.factoryid
     *
     * @mbg.generated
     */
    public Integer getFactoryid() {
        return factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbill.factoryid
     *
     * @param factoryid the value for inbill.factoryid
     *
     * @mbg.generated
     */
    public void setFactoryid(Integer factoryid) {
        this.factoryid = factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbill.time
     *
     * @return the value of inbill.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbill.time
     *
     * @param time the value for inbill.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbill.verifystate
     *
     * @return the value of inbill.verifystate
     *
     * @mbg.generated
     */
    public Integer getVerifystate() {
        return verifystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbill.verifystate
     *
     * @param verifystate the value for inbill.verifystate
     *
     * @mbg.generated
     */
    public void setVerifystate(Integer verifystate) {
        this.verifystate = verifystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbill.allnumber
     *
     * @return the value of inbill.allnumber
     *
     * @mbg.generated
     */
    public Integer getAllnumber() {
        return allnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbill.allnumber
     *
     * @param allnumber the value for inbill.allnumber
     *
     * @mbg.generated
     */
    public void setAllnumber(Integer allnumber) {
        this.allnumber = allnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbill.allprice
     *
     * @return the value of inbill.allprice
     *
     * @mbg.generated
     */
    public Float getAllprice() {
        return allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbill.allprice
     *
     * @param allprice the value for inbill.allprice
     *
     * @mbg.generated
     */
    public void setAllprice(Float allprice) {
        this.allprice = allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbill.remarks
     *
     * @return the value of inbill.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbill.remarks
     *
     * @param remarks the value for inbill.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inbill.addtime
     *
     * @return the value of inbill.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inbill.addtime
     *
     * @param addtime the value for inbill.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}