package com.tmqt.model;

import java.util.Date;

public class Monthcheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthcheck.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthcheck.factoryid
     *
     * @mbg.generated
     */
    private Integer factoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthcheck.month
     *
     * @mbg.generated
     */
    private Date month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthcheck.allmoney
     *
     * @mbg.generated
     */
    private Float allmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthcheck.discountmoney
     *
     * @mbg.generated
     */
    private Float discountmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthcheck.amountpaid
     *
     * @mbg.generated
     */
    private Float amountpaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthcheck.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthcheck.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthcheck.id
     *
     * @return the value of monthcheck.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthcheck.id
     *
     * @param id the value for monthcheck.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthcheck.factoryid
     *
     * @return the value of monthcheck.factoryid
     *
     * @mbg.generated
     */
    public Integer getFactoryid() {
        return factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthcheck.factoryid
     *
     * @param factoryid the value for monthcheck.factoryid
     *
     * @mbg.generated
     */
    public void setFactoryid(Integer factoryid) {
        this.factoryid = factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthcheck.month
     *
     * @return the value of monthcheck.month
     *
     * @mbg.generated
     */
    public Date getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthcheck.month
     *
     * @param month the value for monthcheck.month
     *
     * @mbg.generated
     */
    public void setMonth(Date month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthcheck.allmoney
     *
     * @return the value of monthcheck.allmoney
     *
     * @mbg.generated
     */
    public Float getAllmoney() {
        return allmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthcheck.allmoney
     *
     * @param allmoney the value for monthcheck.allmoney
     *
     * @mbg.generated
     */
    public void setAllmoney(Float allmoney) {
        this.allmoney = allmoney;
    }


    public Float getDiscountmoney() {
        return discountmoney;
    }

    public void setDiscountmoney(Float discountmoney) {
        this.discountmoney = discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthcheck.amountpaid
     *
     * @return the value of monthcheck.amountpaid
     *
     * @mbg.generated
     */
    public Float getAmountpaid() {
        return amountpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthcheck.amountpaid
     *
     * @param amountpaid the value for monthcheck.amountpaid
     *
     * @mbg.generated
     */
    public void setAmountpaid(Float amountpaid) {
        this.amountpaid = amountpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthcheck.addtime
     *
     * @return the value of monthcheck.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthcheck.addtime
     *
     * @param addtime the value for monthcheck.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthcheck.updatetime
     *
     * @return the value of monthcheck.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthcheck.updatetime
     *
     * @param updatetime the value for monthcheck.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}