package com.tmqt.model;

import java.util.Date;
public class Newproduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.starttime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.videostate
     *
     * @mbg.generated
     */
    private Integer videostate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.detailimagestate
     *
     * @mbg.generated
     */
    private Integer detailimagestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.buyershowstate
     *
     * @mbg.generated
     */
    private Integer buyershowstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.testclickstate
     *
     * @mbg.generated
     */
    private Integer testclickstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.stockstate
     *
     * @mbg.generated
     */
    private Integer stockstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newproduct.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.id
     *
     * @return the value of newproduct.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.id
     *
     * @param id the value for newproduct.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.code
     *
     * @return the value of newproduct.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.code
     *
     * @param code the value for newproduct.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.image
     *
     * @return the value of newproduct.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.image
     *
     * @param image the value for newproduct.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.starttime
     *
     * @return the value of newproduct.starttime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.starttime
     *
     * @param starttime the value for newproduct.starttime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.videostate
     *
     * @return the value of newproduct.videostate
     *
     * @mbg.generated
     */
    public Integer getVideostate() {
        return videostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.videostate
     *
     * @param videostate the value for newproduct.videostate
     *
     * @mbg.generated
     */
    public void setVideostate(Integer videostate) {
        this.videostate = videostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.detailimagestate
     *
     * @return the value of newproduct.detailimagestate
     *
     * @mbg.generated
     */
    public Integer getDetailimagestate() {
        return detailimagestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.detailimagestate
     *
     * @param detailimagestate the value for newproduct.detailimagestate
     *
     * @mbg.generated
     */
    public void setDetailimagestate(Integer detailimagestate) {
        this.detailimagestate = detailimagestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.buyershowstate
     *
     * @return the value of newproduct.buyershowstate
     *
     * @mbg.generated
     */
    public Integer getBuyershowstate() {
        return buyershowstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.buyershowstate
     *
     * @param buyershowstate the value for newproduct.buyershowstate
     *
     * @mbg.generated
     */
    public void setBuyershowstate(Integer buyershowstate) {
        this.buyershowstate = buyershowstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.testclickstate
     *
     * @return the value of newproduct.testclickstate
     *
     * @mbg.generated
     */
    public Integer getTestclickstate() {
        return testclickstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.testclickstate
     *
     * @param testclickstate the value for newproduct.testclickstate
     *
     * @mbg.generated
     */
    public void setTestclickstate(Integer testclickstate) {
        this.testclickstate = testclickstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.stockstate
     *
     * @return the value of newproduct.stockstate
     *
     * @mbg.generated
     */
    public Integer getStockstate() {
        return stockstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.stockstate
     *
     * @param stockstate the value for newproduct.stockstate
     *
     * @mbg.generated
     */
    public void setStockstate(Integer stockstate) {
        this.stockstate = stockstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.remarks
     *
     * @return the value of newproduct.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.remarks
     *
     * @param remarks the value for newproduct.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newproduct.addtime
     *
     * @return the value of newproduct.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newproduct.addtime
     *
     * @param addtime the value for newproduct.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}