package com.tmqt.model;

import java.util.Date;

public class Outbill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbill.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbill.factoryid
     *
     * @mbg.generated
     */
    private Integer factoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbill.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbill.verifystate
     *
     * @mbg.generated
     */
    private Integer verifystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbill.atmonth
     *
     * @mbg.generated
     */
    private Date atmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbill.allnumber
     *
     * @mbg.generated
     */
    private Integer allnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbill.allprice
     *
     * @mbg.generated
     */
    private Float allprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbill.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbill.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbill.id
     *
     * @return the value of outbill.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbill.id
     *
     * @param id the value for outbill.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbill.factoryid
     *
     * @return the value of outbill.factoryid
     *
     * @mbg.generated
     */
    public Integer getFactoryid() {
        return factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbill.factoryid
     *
     * @param factoryid the value for outbill.factoryid
     *
     * @mbg.generated
     */
    public void setFactoryid(Integer factoryid) {
        this.factoryid = factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbill.time
     *
     * @return the value of outbill.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbill.time
     *
     * @param time the value for outbill.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbill.verifystate
     *
     * @return the value of outbill.verifystate
     *
     * @mbg.generated
     */
    public Integer getVerifystate() {
        return verifystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbill.verifystate
     *
     * @param verifystate the value for outbill.verifystate
     *
     * @mbg.generated
     */
    public void setVerifystate(Integer verifystate) {
        this.verifystate = verifystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbill.atmonth
     *
     * @return the value of outbill.atmonth
     *
     * @mbg.generated
     */
    public Date getAtmonth() {
        return atmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbill.atmonth
     *
     * @param atmonth the value for outbill.atmonth
     *
     * @mbg.generated
     */
    public void setAtmonth(Date atmonth) {
        this.atmonth = atmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbill.allnumber
     *
     * @return the value of outbill.allnumber
     *
     * @mbg.generated
     */
    public Integer getAllnumber() {
        return allnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbill.allnumber
     *
     * @param allnumber the value for outbill.allnumber
     *
     * @mbg.generated
     */
    public void setAllnumber(Integer allnumber) {
        this.allnumber = allnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbill.allprice
     *
     * @return the value of outbill.allprice
     *
     * @mbg.generated
     */
    public Float getAllprice() {
        return allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbill.allprice
     *
     * @param allprice the value for outbill.allprice
     *
     * @mbg.generated
     */
    public void setAllprice(Float allprice) {
        this.allprice = allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbill.remarks
     *
     * @return the value of outbill.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbill.remarks
     *
     * @param remarks the value for outbill.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outbill.addtime
     *
     * @return the value of outbill.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outbill.addtime
     *
     * @param addtime the value for outbill.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}