package com.tmqt.model;

import java.util.Date;

public class Payment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.factoryid
     *
     * @mbg.generated
     */
    private Integer factoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.month
     *
     * @mbg.generated
     */
    private Date month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.money
     *
     * @mbg.generated
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.paytime
     *
     * @mbg.generated
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.adddtime
     *
     * @mbg.generated
     */
    private Date adddtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.id
     *
     * @return the value of payment.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.id
     *
     * @param id the value for payment.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.type
     *
     * @return the value of payment.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.type
     *
     * @param type the value for payment.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.factoryid
     *
     * @return the value of payment.factoryid
     *
     * @mbg.generated
     */
    public Integer getFactoryid() {
        return factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.factoryid
     *
     * @param factoryid the value for payment.factoryid
     *
     * @mbg.generated
     */
    public void setFactoryid(Integer factoryid) {
        this.factoryid = factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.month
     *
     * @return the value of payment.month
     *
     * @mbg.generated
     */
    public Date getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.month
     *
     * @param month the value for payment.month
     *
     * @mbg.generated
     */
    public void setMonth(Date month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.money
     *
     * @return the value of payment.money
     *
     * @mbg.generated
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.money
     *
     * @param money the value for payment.money
     *
     * @mbg.generated
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.paytime
     *
     * @return the value of payment.paytime
     *
     * @mbg.generated
     */
    public Date getPaytime() {
        return paytime;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.remarks
     *
     * @return the value of payment.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.paytime
     *
     * @param paytime the value for payment.paytime
     *
     * @mbg.generated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.adddtime
     *
     * @return the value of payment.adddtime
     *
     * @mbg.generated
     */
    public Date getAdddtime() {
        return adddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.adddtime
     *
     * @param adddtime the value for payment.adddtime
     *
     * @mbg.generated
     */
    public void setAdddtime(Date adddtime) {
        this.adddtime = adddtime;
    }
}