package com.tmqt.model;

import java.util.Date;

public class Productplan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.material
     *
     * @mbg.generated
     */
    private String material;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.insidefabric
     *
     * @mbg.generated
     */
    private String insidefabric;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.bottommaterial
     *
     * @mbg.generated
     */
    private String bottommaterial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.factory
     *
     * @mbg.generated
     */
    private String factory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.cost
     *
     * @mbg.generated
     */
    private String cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.price
     *
     * @mbg.generated
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.titlestate
     *
     * @mbg.generated
     */
    private Integer titlestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.brand
     *
     * @mbg.generated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.takelength
     *
     * @mbg.generated
     */
    private Integer takelength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.dctime
     *
     * @mbg.generated
     */
    private Date dctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.altime
     *
     * @mbg.generated
     */
    private Date altime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.kdtime
     *
     * @mbg.generated
     */
    private Date kdtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.tmtime
     *
     * @mbg.generated
     */
    private Date tmtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.dcpre
     *
     * @mbg.generated
     */
    private Integer dcpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.alpre
     *
     * @mbg.generated
     */
    private Integer alpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.kdpre
     *
     * @mbg.generated
     */
    private Integer kdpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.tmpre
     *
     * @mbg.generated
     */
    private Integer tmpre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.prephototime
     *
     * @mbg.generated
     */
    private Date prephototime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productplan.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.id
     *
     * @return the value of productplan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.id
     *
     * @param id the value for productplan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.code
     *
     * @return the value of productplan.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.code
     *
     * @param code the value for productplan.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.image
     *
     * @return the value of productplan.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.image
     *
     * @param image the value for productplan.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.material
     *
     * @return the value of productplan.material
     *
     * @mbg.generated
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.material
     *
     * @param material the value for productplan.material
     *
     * @mbg.generated
     */
    public void setMaterial(String material) {
        this.material = material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.insidefabric
     *
     * @return the value of productplan.insidefabric
     *
     * @mbg.generated
     */
    public String getInsidefabric() {
        return insidefabric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.insidefabric
     *
     * @param insidefabric the value for productplan.insidefabric
     *
     * @mbg.generated
     */
    public void setInsidefabric(String insidefabric) {
        this.insidefabric = insidefabric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.bottommaterial
     *
     * @return the value of productplan.bottommaterial
     *
     * @mbg.generated
     */
    public String getBottommaterial() {
        return bottommaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.bottommaterial
     *
     * @param bottommaterial the value for productplan.bottommaterial
     *
     * @mbg.generated
     */
    public void setBottommaterial(String bottommaterial) {
        this.bottommaterial = bottommaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.type
     *
     * @return the value of productplan.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.type
     *
     * @param type the value for productplan.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.color
     *
     * @return the value of productplan.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.color
     *
     * @param color the value for productplan.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.factory
     *
     * @return the value of productplan.factory
     *
     * @mbg.generated
     */
    public String getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.factory
     *
     * @param factory the value for productplan.factory
     *
     * @mbg.generated
     */
    public void setFactory(String factory) {
        this.factory = factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.cost
     *
     * @return the value of productplan.cost
     *
     * @mbg.generated
     */
    public String getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.cost
     *
     * @param cost the value for productplan.cost
     *
     * @mbg.generated
     */
    public void setCost(String cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.price
     *
     * @return the value of productplan.price
     *
     * @mbg.generated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.price
     *
     * @param price the value for productplan.price
     *
     * @mbg.generated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.titlestate
     *
     * @return the value of productplan.titlestate
     *
     * @mbg.generated
     */
    public Integer getTitlestate() {
        return titlestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.titlestate
     *
     * @param titlestate the value for productplan.titlestate
     *
     * @mbg.generated
     */
    public void setTitlestate(Integer titlestate) {
        this.titlestate = titlestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.brand
     *
     * @return the value of productplan.brand
     *
     * @mbg.generated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.brand
     *
     * @param brand the value for productplan.brand
     *
     * @mbg.generated
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.takelength
     *
     * @return the value of productplan.takelength
     *
     * @mbg.generated
     */
    public Integer getTakelength() {
        return takelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.takelength
     *
     * @param takelength the value for productplan.takelength
     *
     * @mbg.generated
     */
    public void setTakelength(Integer takelength) {
        this.takelength = takelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.dctime
     *
     * @return the value of productplan.dctime
     *
     * @mbg.generated
     */
    public Date getDctime() {
        return dctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.dctime
     *
     * @param dctime the value for productplan.dctime
     *
     * @mbg.generated
     */
    public void setDctime(Date dctime) {
        this.dctime = dctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.altime
     *
     * @return the value of productplan.altime
     *
     * @mbg.generated
     */
    public Date getAltime() {
        return altime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.altime
     *
     * @param altime the value for productplan.altime
     *
     * @mbg.generated
     */
    public void setAltime(Date altime) {
        this.altime = altime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.kdtime
     *
     * @return the value of productplan.kdtime
     *
     * @mbg.generated
     */
    public Date getKdtime() {
        return kdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.kdtime
     *
     * @param kdtime the value for productplan.kdtime
     *
     * @mbg.generated
     */
    public void setKdtime(Date kdtime) {
        this.kdtime = kdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.tmtime
     *
     * @return the value of productplan.tmtime
     *
     * @mbg.generated
     */
    public Date getTmtime() {
        return tmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.tmtime
     *
     * @param tmtime the value for productplan.tmtime
     *
     * @mbg.generated
     */
    public void setTmtime(Date tmtime) {
        this.tmtime = tmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.dcpre
     *
     * @return the value of productplan.dcpre
     *
     * @mbg.generated
     */
    public Integer getDcpre() {
        return dcpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.dcpre
     *
     * @param dcpre the value for productplan.dcpre
     *
     * @mbg.generated
     */
    public void setDcpre(Integer dcpre) {
        this.dcpre = dcpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.alpre
     *
     * @return the value of productplan.alpre
     *
     * @mbg.generated
     */
    public Integer getAlpre() {
        return alpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.alpre
     *
     * @param alpre the value for productplan.alpre
     *
     * @mbg.generated
     */
    public void setAlpre(Integer alpre) {
        this.alpre = alpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.kdpre
     *
     * @return the value of productplan.kdpre
     *
     * @mbg.generated
     */
    public Integer getKdpre() {
        return kdpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.kdpre
     *
     * @param kdpre the value for productplan.kdpre
     *
     * @mbg.generated
     */
    public void setKdpre(Integer kdpre) {
        this.kdpre = kdpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.tmpre
     *
     * @return the value of productplan.tmpre
     *
     * @mbg.generated
     */
    public Integer getTmpre() {
        return tmpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.tmpre
     *
     * @param tmpre the value for productplan.tmpre
     *
     * @mbg.generated
     */
    public void setTmpre(Integer tmpre) {
        this.tmpre = tmpre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.prephototime
     *
     * @return the value of productplan.prephototime
     *
     * @mbg.generated
     */
    public Date getPrephototime() {
        return prephototime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.prephototime
     *
     * @param prephototime the value for productplan.prephototime
     *
     * @mbg.generated
     */
    public void setPrephototime(Date prephototime) {
        this.prephototime = prephototime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.remarks
     *
     * @return the value of productplan.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.remarks
     *
     * @param remarks the value for productplan.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productplan.addtime
     *
     * @return the value of productplan.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productplan.addtime
     *
     * @param addtime the value for productplan.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}