package com.tmqt.model;

import java.util.Date;

public class Purchase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.billid
     *
     * @mbg.generated
     */
    private String billid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.factoryid
     *
     * @mbg.generated
     */
    private Integer factoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.rangesize
     *
     * @mbg.generated
     */
    private String rangesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.price
     *
     * @mbg.generated
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.allprice
     *
     * @mbg.generated
     */
    private Float allprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.id
     *
     * @return the value of purchase.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.id
     *
     * @param id the value for purchase.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.billid
     *
     * @return the value of purchase.billid
     *
     * @mbg.generated
     */
    public String getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.billid
     *
     * @param billid the value for purchase.billid
     *
     * @mbg.generated
     */
    public void setBillid(String billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.time
     *
     * @return the value of purchase.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.time
     *
     * @param time the value for purchase.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.factoryid
     *
     * @return the value of purchase.factoryid
     *
     * @mbg.generated
     */
    public Integer getFactoryid() {
        return factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.factoryid
     *
     * @param factoryid the value for purchase.factoryid
     *
     * @mbg.generated
     */
    public void setFactoryid(Integer factoryid) {
        this.factoryid = factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.code
     *
     * @return the value of purchase.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.code
     *
     * @param code the value for purchase.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.rangesize
     *
     * @return the value of purchase.rangesize
     *
     * @mbg.generated
     */
    public String getRangesize() {
        return rangesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.rangesize
     *
     * @param rangesize the value for purchase.rangesize
     *
     * @mbg.generated
     */
    public void setRangesize(String rangesize) {
        this.rangesize = rangesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.color
     *
     * @return the value of purchase.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.color
     *
     * @param color the value for purchase.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.price
     *
     * @return the value of purchase.price
     *
     * @mbg.generated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.price
     *
     * @param price the value for purchase.price
     *
     * @mbg.generated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.number
     *
     * @return the value of purchase.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.number
     *
     * @param number the value for purchase.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.allprice
     *
     * @return the value of purchase.allprice
     *
     * @mbg.generated
     */
    public Float getAllprice() {
        return allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.allprice
     *
     * @param allprice the value for purchase.allprice
     *
     * @mbg.generated
     */
    public void setAllprice(Float allprice) {
        this.allprice = allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.remarks
     *
     * @return the value of purchase.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.remarks
     *
     * @param remarks the value for purchase.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.addtime
     *
     * @return the value of purchase.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.addtime
     *
     * @param addtime the value for purchase.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}