package com.tmqt.model;

import java.util.Date;

public class Rangesize {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rangesize.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rangesize.rangesize
     *
     * @mbg.generated
     */
    private String rangesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rangesize.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rangesize.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangesize.id
     *
     * @return the value of rangesize.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangesize.id
     *
     * @param id the value for rangesize.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangesize.rangesize
     *
     * @return the value of rangesize.rangesize
     *
     * @mbg.generated
     */
    public String getRangesize() {
        return rangesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangesize.rangesize
     *
     * @param rangesize the value for rangesize.rangesize
     *
     * @mbg.generated
     */
    public void setRangesize(String rangesize) {
        this.rangesize = rangesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangesize.remarks
     *
     * @return the value of rangesize.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangesize.remarks
     *
     * @param remarks the value for rangesize.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rangesize.addtime
     *
     * @return the value of rangesize.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rangesize.addtime
     *
     * @param addtime the value for rangesize.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}