package com.tmqt.model;

import java.util.Date;

public class Returns {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.billid
     *
     * @mbg.generated
     */
    private String billid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.atmonth
     *
     * @mbg.generated
     */
    private Date atmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.factoryid
     *
     * @mbg.generated
     */
    private Integer factoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.rangesize
     *
     * @mbg.generated
     */
    private String rangesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.price
     *
     * @mbg.generated
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.allprice
     *
     * @mbg.generated
     */
    private Float allprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column returns.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.id
     *
     * @return the value of returns.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.id
     *
     * @param id the value for returns.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.billid
     *
     * @return the value of returns.billid
     *
     * @mbg.generated
     */
    public String getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.billid
     *
     * @param billid the value for returns.billid
     *
     * @mbg.generated
     */
    public void setBillid(String billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.time
     *
     * @return the value of returns.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.time
     *
     * @param time the value for returns.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.atmonth
     *
     * @return the value of returns.atmonth
     *
     * @mbg.generated
     */
    public Date getAtmonth() {
        return atmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.atmonth
     *
     * @param atmonth the value for returns.atmonth
     *
     * @mbg.generated
     */
    public void setAtmonth(Date atmonth) {
        this.atmonth = atmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.factoryid
     *
     * @return the value of returns.factoryid
     *
     * @mbg.generated
     */
    public Integer getFactoryid() {
        return factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.factoryid
     *
     * @param factoryid the value for returns.factoryid
     *
     * @mbg.generated
     */
    public void setFactoryid(Integer factoryid) {
        this.factoryid = factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.code
     *
     * @return the value of returns.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.code
     *
     * @param code the value for returns.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.rangesize
     *
     * @return the value of returns.rangesize
     *
     * @mbg.generated
     */
    public String getRangesize() {
        return rangesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.rangesize
     *
     * @param rangesize the value for returns.rangesize
     *
     * @mbg.generated
     */
    public void setRangesize(String rangesize) {
        this.rangesize = rangesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.color
     *
     * @return the value of returns.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.color
     *
     * @param color the value for returns.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.price
     *
     * @return the value of returns.price
     *
     * @mbg.generated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.price
     *
     * @param price the value for returns.price
     *
     * @mbg.generated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.number
     *
     * @return the value of returns.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.number
     *
     * @param number the value for returns.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.allprice
     *
     * @return the value of returns.allprice
     *
     * @mbg.generated
     */
    public Float getAllprice() {
        return allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.allprice
     *
     * @param allprice the value for returns.allprice
     *
     * @mbg.generated
     */
    public void setAllprice(Float allprice) {
        this.allprice = allprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.remarks
     *
     * @return the value of returns.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.remarks
     *
     * @param remarks the value for returns.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column returns.addtime
     *
     * @return the value of returns.addtime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column returns.addtime
     *
     * @param addtime the value for returns.addtime
     *
     * @mbg.generated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}